---
name: update
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    name: ${{ matrix.os }}-py${{ matrix.python }}-torch${{ matrix.pytorch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        pytorch:
          - "v1.5.0"
          - "v1.4.0"
          - "latest"
        python:
          - 3.6
          - 3.7
          - 3.8
        os:
          - ubuntu-latest
          - ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Update torchlambda version
        run: ./scripts/release/update_version.sh
      - name: Install dependencies
        run: ./scripts/ci/dependencies.sh
      - name: Build docker image locally
        run: ./scripts/ci/build.sh ${{ matrix.pytorch }}
      - name: Perform tests
        run: ./tests/settings/automated/run.sh ${{ matrix.pytorch }}
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-py${{ matrix.python }}-torch${{ matrix.pytorch }}.npz
          path: analysis.npz

  docker:
    needs: tests
    if: github.event_name == 'schedule'
    name: Deployment image szymonmaszke/torchlambda:${{ matrix.pytorch}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytorch:
          - "v1.5.0"
          - "v1.4.0"
          - "latest"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update torchlambda version
        run: ./scripts/release/update_version.sh
      - name: Install dependencies
        run: ./scripts/ci/dependencies.sh
      - name: Build docker image locally
        run: ./scripts/ci/build.sh ${{ matrix.pytorch }}
      - name: Login to Docker
        run: >
          docker login
          -u ${{ secrets.DOCKER_USERNAME }}
          -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy image szymonmaszke/torchlambda:${{ matrix.pytorch }}
        run: >
          docker push szymonmaszke/torchlambda:${{ matrix.pytorch }}

  pip:
    needs: tests
    if: github.event_name == 'schedule'
    name: Create and publish package to PyPI with current timestamp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update torchlambda version
        run: ./scripts/release/update_version.sh
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
